name: Keep Supabase Awake

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Wake Supabase
        run: |
          curl \
          -X GET \
          -H "x-secret: ${{ secrets.KEEPALIVE_SECRET }}" \
          https://uemntbuhsjwnognsmlaq.supabase.co/functions/v1/keepalive
