name: Wake Supabase

on:
  workflow_dispatch:

  schedule:
    - cron: '0 */6 * * *'

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Database
        run: |
          curl \
          "https://uemntbuhsjwnognsmlaq.supabase.co/rest/v1/subscriptions?select=id&limit=1" \
          -H "apikey: ${{ secrets.KEEPALIVE_SECRET }}"
